import React from 'react';
import { motion } from 'motion/react';
import { Shield, MessageSquare, Bell, Lock, ChevronLeft, Info } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const AppPermissions: React.FC = () => {
  const navigate = useNavigate();

  const permissions = [
    {
      title: "SMS Access",
      rationale: "WealthOS uses SMS access to automatically sync your transaction alerts from banks and digital wallets. This ensures your dashboard is always up-to-date without manual entry.",
      privacy: "Only financial transaction alerts are processed. Personal messages never leave your device.",
      icon: MessageSquare,
      color: "text-blue-600",
      bgColor: "bg-blue-50"
    },
    {
      title: "Notifications",
      rationale: "We send you timely alerts for budget breakthroughs, upcoming EMI dues, and smart wealth insights generated by your financial assistant.",
      privacy: "You can customize or disable these alerts at any time in the Notifications settings.",
      icon: Bell,
      color: "text-amber-600",
      bgColor: "bg-amber-50"
    },
    {
      title: "Storage & Cache",
      rationale: "The app stores temporary data locally to ensure fast performance and offline access to your recent financial snapshots.",
      privacy: "This data is encrypted and strictly managed by the Android/iOS system containers.",
      icon: Shield,
      color: "text-emerald-600",
      bgColor: "bg-emerald-50"
    }
  ];

  return (
    <div className="max-w-3xl mx-auto py-12 px-6">
      <button 
        onClick={() => navigate(-1)}
        className="flex items-center text-gray-500 hover:text-indigo-600 transition-colors mb-8 font-bold"
      >
        <ChevronLeft className="w-5 h-5 mr-1" />
        Back to Settings
      </button>

      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-12"
      >
        <div className="w-16 h-16 bg-rose-600 rounded-2xl flex items-center justify-center mb-6 shadow-xl shadow-rose-100">
          <Lock className="w-8 h-8 text-white" />
        </div>
        <h1 className="text-4xl font-black text-gray-900 tracking-tight mb-4">Transparency & Permissions</h1>
        <p className="text-xl text-gray-500">How and why WealthOS requests access to your device.</p>
      </motion.div>

      <div className="space-y-6">
        {permissions.map((p, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: i * 0.1 }}
            className="bg-white rounded-[2rem] p-8 border border-gray-100 shadow-sm"
          >
            <div className="flex items-start gap-6">
              <div className={`w-14 h-14 ${p.bgColor} ${p.color} rounded-2xl flex items-center justify-center shrink-0`}>
                <p.icon className="w-7 h-7" />
              </div>
              <div className="space-y-4">
                <h3 className="text-xl font-black text-gray-900">{p.title}</h3>
                <div>
                  <h4 className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Our Purpose</h4>
                  <p className="text-gray-600 leading-relaxed font-medium">{p.rationale}</p>
                </div>
                <div className="bg-gray-50 p-4 rounded-xl flex items-start gap-3">
                  <Info className="w-4 h-4 text-gray-400 shrink-0 mt-0.5" />
                  <div>
                    <h4 className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Privacy Guarantee</h4>
                    <p className="text-xs text-gray-500 italic">{p.privacy}</p>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      <div className="mt-12 p-8 bg-indigo-600 rounded-[2.5rem] text-white text-center">
        <h3 className="text-2xl font-black mb-4">Your Trust is Our Wealth</h3>
        <p className="text-indigo-100 mb-0 leading-relaxed max-w-lg mx-auto">
          We follow strict Play Store and App Store policies on data security. Your financial data is yours, and we only use it to empower your growth.
        </p>
      </div>
    </div>
  );
};

export default AppPermissions;
